// Generates the virtual cohort for the Diastolic lab: N patients per grade, each the grade's parameters
// with individual log-normal variation, run through the volume, afterload, surge and AF protocols, plus
// the fluid-then-diuresis time course for each grade's reference patient.
// Writes site/js/diastdata.js (read by the page) and R/diastolic_*.csv (for analysis in R).
//   node tools/diastolic_cohort.mjs [N=40] [seed=2026]
// Each grade runs in its own worker thread.
import { Worker, isMainThread, parentPort, workerData } from 'node:worker_threads';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { NORMAL } from '../site/js/engine.js';
import { GRADES, JITTER, individual, rng, protocol, tolerance, course, FIELDS } from '../site/js/diastcore.js';

const here = fileURLToPath(import.meta.url);
const root = new URL('..', import.meta.url);

function runGrade({ g, N, seed }) {
  const u = rng(seed + 1000 * g);
  const patients = [];
  const ref = { id: `${GRADES[g].key}-ref`, grade: g, ref: true, params: GRADES[g].params };
  for (const pt of [ref, ...Array.from({ length: N }, (_, i) => ({ id: `${GRADES[g].key}-${String(i + 1).padStart(3, '0')}`, grade: g, params: individual(g, u) }))]) {
    const rows = protocol(pt.params);
    patients.push({ ...pt, rows, tol: tolerance(rows) });
  }
  return { g, patients, course: course(GRADES[g].params) };
}

if (!isMainThread) {
  parentPort.postMessage(runGrade(workerData));
} else {
  const N = +(process.argv[2] ?? 40), seed = +(process.argv[3] ?? 2026);
  const t0 = Date.now();
  const results = await Promise.all(GRADES.map((_, g) => new Promise((res, rej) => {
    const w = new Worker(here, { workerData: { g, N, seed } });
    w.on('message', res); w.on('error', rej);
  })));
  results.sort((a, b) => a.g - b.g);
  const r3 = (v) => (Number.isFinite(v) ? +v.toPrecision(4) : null);

  // Page data: compact rows (the fields the charts read), tolerance, and the reference course.
  const PF = ['CO', 'SV', 'MAP', 'LAP', 'mPAP', 'EA', 'Eep', 'echoGrade', 'EDV', 'EDP'];
  const conds = results[0].patients[0].rows.map((r) => [r.kind, r.x]);
  const data = {
    N, seed, generated: new Date().toISOString().slice(0, 10), fields: PF, conds,
    grades: results.map(({ g, patients, course: c }) => ({
      g,
      patients: patients.map((p) => ({ id: p.id, ref: !!p.ref, rows: p.rows.map((r) => PF.map((k) => r3(r[k]))),
        tol: Object.fromEntries(Object.entries(p.tol).map(([k, v]) => [k, r3(v)])) })),
      course: c.map((r) => ({ t: r.t, vol: r3(r.vol), ...Object.fromEntries(PF.map((k) => [k, r3(r[k])])) })),
    })),
  };
  writeFileSync(new URL('site/js/diastdata.js', root),
    `// Generated by tools/diastolic_cohort.mjs (N = ${N} per grade, seed ${seed}); do not edit by hand.\n` +
    `export const COHORT = ${JSON.stringify(data)};\n`);

  // CSV for R: long protocol table, one row per patient per condition; patient summary; time courses.
  const csv = (rows) => rows.map((r) => r.map((v) => (typeof v === 'string' ? `"${v}"` : v == null || Number.isNaN(v) ? 'NA' : Number.isFinite(v) ? +v.toPrecision(5) : 'Inf')).join(',')).join('\n') + '\n';
  const PK = Object.keys(JITTER);
  const long = [['id', 'grade', 'ref', ...PK, 'protocol', 'x', ...FIELDS]];
  const summ = [['id', 'grade', 'ref', ...PK, ...Object.keys(results[0].patients[0].tol)]];
  const full = (p) => PK.map((k) => ({ ...NORMAL, ...p.params })[k]);
  for (const { patients } of results) for (const p of patients) {
    for (const r of p.rows) long.push([p.id, p.grade, p.ref ? 1 : 0, ...full(p), r.kind, r.x, ...FIELDS.map((k) => r[k])]);
    summ.push([p.id, p.grade, p.ref ? 1 : 0, ...full(p), ...Object.values(p.tol)]);
  }
  const cr = [['grade', 't_min', 'vol_mL', ...FIELDS]];
  for (const { g, course: c } of results) for (const r of c) cr.push([g, r.t, r.vol, ...FIELDS.map((k) => r[k])]);
  writeFileSync(new URL('R/diastolic_cohort_long.csv', root), csv(long));
  writeFileSync(new URL('R/diastolic_cohort_summary.csv', root), csv(summ));
  writeFileSync(new URL('R/diastolic_course.csv', root), csv(cr));
  console.log(`${results.reduce((a, r) => a + r.patients.length, 0)} patients in ${((Date.now() - t0) / 1000).toFixed(0)} s`);
}
